use_frameworks!

platform :ios, '12.0'

target 'Rudder-Branch_Example' do
  pod 'Rudder-Branch', :path => '../'

  target 'Rudder-Branch_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
