use_frameworks!

platform :ios, '15.0'

target 'Rudder-Branch_Example' do
  pod 'Rudder-Branch', :path => '../'

  target 'Rudder-Branch_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
